# Generated by Django 5.2.6 on 2026-08-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcardset',
            name='show_answer_first',
            field=models.BooleanField(default=False, verbose_name='Показывать ответ первым'),
        ),
    ]
