# Generated by Django 5.2.6 on 2025-12-11 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flashcards', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Начало сессии')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Окончание сессии')),
                ('cards_studied', models.IntegerField(default=0, verbose_name='Количество изучаемых карточек')),
                ('cards_known', models.IntegerField(default=0, verbose_name='Количество изученных слов за сессию')),
            ],
            options={
                'verbose_name': 'Сессия изучения',
                'verbose_name_plural': 'Сессии изучения',
            },
        ),
        migrations.CreateModel(
            name='CardProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_known', models.BooleanField(default=False, verbose_name='Знает/Не знает термин?')),
                ('date_answer', models.DateTimeField(auto_now=True, verbose_name='Дата ответа')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashcards.card', verbose_name='Изучающая карточка')),
            ],
            options={
                'verbose_name': 'Прогресс карточки',
                'verbose_name_plural': 'Прогресс карточек',
            },
        ),
    ]
