# Generated by Django 5.2.6 on 2025-12-11 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flashcards', '0002_initial'),
        ('study', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cardprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Изучающий'),
        ),
        migrations.AddField(
            model_name='studysession',
            name='flashcard_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='flashcards.flashcardset', verbose_name='Набор карточек'),
        ),
        migrations.AddField(
            model_name='studysession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь изучающий карточки'),
        ),
        migrations.AddConstraint(
            model_name='cardprogress',
            constraint=models.UniqueConstraint(fields=('user', 'card'), name='unique_user_card'),
        ),
        migrations.AddConstraint(
            model_name='studysession',
            constraint=models.UniqueConstraint(fields=('user', 'flashcard_set'), name='unique_user_flashcard_set'),
        ),
    ]
