# Generated by Django 5.2.6 on 2025-12-13 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_initial'),
        ('study', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cardprogress',
            name='unique_user_card',
        ),
        migrations.AddField(
            model_name='cardprogress',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='study.studysession', verbose_name='Сессия'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='cardprogress',
            constraint=models.UniqueConstraint(fields=('user', 'card', 'session'), name='unique_user_card_session'),
        ),
    ]
