# Generated by Django 5.2.6 on 2025-10-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardprogress',
            name='date_answer',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата ответа'),
        ),
    ]
