# Generated by Django 5.2.6 on 2026-01-24 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='social_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Уникальны код соц. приложения'),
        ),
        migrations.AddField(
            model_name='user',
            name='social_provider',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='С какой соц. сети зарег. пользователь'),
        ),
    ]
