"""
Django's settings for conf project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from datetime import timedelta
from pathlib import Path
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(BASE_DIR))  # Добавляем корень проекта
sys.path.insert(0, os.path.join(BASE_DIR, 'backend_apps'))  # Добавляем папку с приложениями
# Подключаем виртуальную среду
env = environ.Env()
environ.Env.read_env(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=False)

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS')

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'silk',  # для оптимизации запросов silk
    'rest_framework',  # drf
    'rest_framework_simplejwt',  # JWT авторизация\регистрация по токенам
    'drf_yasg',  # для документирования api
    'corsheaders',  # для возможности фронта отправлять запросы на django

    # local
    'backend_apps.users.apps.UsersConfig',
    'backend_apps.auth_api.apps.AuthApiConfig',
    'backend_apps.media.apps.MediaConfig',
    'backend_apps.folders.apps.FoldersConfig',
    'backend_apps.courses.apps.CoursesConfig',
    'backend_apps.flashcards.apps.FlashcardsConfig',
    'backend_apps.study.apps.StudyConfig',

]
# Опциональные настройки Swagger
SWAGGER_SETTINGS = {
    'DEFAULT_INFO': 'conf.yasg.schema_view',
    'USE_SESSION_AUTH': False,
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header',
            'description': 'JWT токен в формате: Bearer <token>'
        }
    },
}

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',  # для пагинации
    'PAGE_SIZE': 25,  # для пагинации

    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',  # Аутентификация через JWT-токены
        'rest_framework.authentication.SessionAuthentication',  # Аутентификация по сессии, для админки
    ),
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend'
    ],
    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema'  # swagger для документации API
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=5),  # продолжительность жизни токена ACCESS
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),  # продолжительность жизни токена REFRESH
    "ROTATE_REFRESH_TOKENS": True,  # Генерировать новый refresh при использовании
    "BLACKLIST_AFTER_ROTATION": True,  # Блокировать старый refresh
}

MIDDLEWARE = [
    'silk.middleware.SilkyMiddleware',  # для отслеживания количества запросов silk

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',

    'corsheaders.middleware.CorsMiddleware',  # для возможности фронта отправлять запросы на django
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

ROOT_URLCONF = 'conf.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'conf.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": "mydatabase",
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': env('DB_NAME'),
        'USER': env('DB_USER'),
        'PASSWORD': env('DB_PASSWORD'),
        'HOST': env('DB_HOST', default='localhost'),
        'PORT': '',
    }
}

# указываем на пользовательскую модель
AUTH_USER_MODEL = 'users.User'

# Mongo_BD
MONGO_URI = os.getenv("MONGO_URI", "mongodb://localhost:27017/")
MONGO_DB_NAME = os.getenv("MONGO_DB_NAME", "flashcard_snapshots")

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/django-static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Медиа файлы
MEDIA_URL = '/files/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'files')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# разрешенные подключения
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    # адреса в продакшн-сервера
    "http://155.212.145.145",  # IP-адрес сервера
    "http://re-call.ru",  # Основной домен
    "http://re-call.store",
]

GOOGLE_REDIRECT_URI = env('GOOGLE_REDIRECT_URI')  # для соц. аут\рег через гугл

AUTH_GITHUB_KEY = env('AUTH_GITHUB_KEY')
AUTH_GITHUB_SECRET = env('AUTH_GITHUB_SECRET')
AUTH_GOOGLE_OAUTH2_KEY = env('AUTH_GOOGLE_OAUTH2_KEY')
AUTH_GOOGLE_OAUTH2_SECRET = env('AUTH_GOOGLE_OAUTH2_SECRET')

EMAIL_BACKEND = env('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = env('EMAIL_HOST', default='localhost')
EMAIL_PORT = env.int('EMAIL_PORT', default=25)
EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS', default=False)
EMAIL_USE_SSL = env.bool('EMAIL_USE_SSL', default=False)
EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default='noreply@re-call.ru')
SERVER_EMAIL = 'noreply@re-call.ru'
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend' # для локальной разработки
