# Generated by Django 5.2.6 on 2025-12-11 17:36

import backend_apps.media.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновление данных')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('path_file', models.ImageField(upload_to='files/images/%Y/%m/%d', validators=[backend_apps.media.models.SizeValueValidator(max_size_mb=3)], verbose_name='Ссылка на файл')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Sound',
            fields=[
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновление данных')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('path_file', backend_apps.media.models.SoundField(upload_to='files/sounds/%Y/%m/%d', validators=[backend_apps.media.models.SoundField.validate_audio_file, backend_apps.media.models.SoundField.validate_audio_file_use_mutagen, backend_apps.media.models.SoundField.validate_audio_file, backend_apps.media.models.SoundField.validate_audio_file_use_mutagen], verbose_name='Ссылка на файл')),
            ],
            options={
                'verbose_name': 'Произношение',
                'verbose_name_plural': 'Произношения',
                'ordering': ['-created'],
            },
        ),
    ]
