# Generated by Django 5.2.6 on 2025-12-13 09:53

import backend_apps.media.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sound',
            name='path_file',
            field=backend_apps.media.models.SoundField(upload_to='files/sounds/%Y/%m/%d', validators=[backend_apps.media.models.SoundField.validate_audio_file, backend_apps.media.models.SoundField.validate_audio_file_use_mutagen, backend_apps.media.models.SoundField.validate_audio_file, backend_apps.media.models.SoundField.validate_audio_file_use_mutagen], verbose_name='Ссылка на файл'),
        ),
    ]
