# Generated by Django 5.2.6 on 2026-01-11 17:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('folders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновление данных')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_public', models.BooleanField(default=False, verbose_name='Публичный курс')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_courses', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='folders.folder', verbose_name='Папка, в которой находится курс')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='CourseLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Лайк курса',
                'verbose_name_plural': 'Лайки курсов',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_courses', through='courses.CourseLike', to=settings.AUTH_USER_MODEL, verbose_name='Лайки курса'),
        ),
        migrations.CreateModel(
            name='CourseStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('teacher', 'Преподаватель'), ('student', 'Студент'), ('admin', 'Администратор')], default='student', max_length=10, verbose_name='Роль')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Дата записи')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='Курс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studying_courses', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Участник курса',
                'verbose_name_plural': 'Участники курсов',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(related_name='+', through='courses.CourseStudent', to=settings.AUTH_USER_MODEL, verbose_name='Записанные на курс студенты'),
        ),
        migrations.AddConstraint(
            model_name='courselike',
            constraint=models.UniqueConstraint(fields=('course', 'user'), name='unique_course_like'),
        ),
        migrations.AddConstraint(
            model_name='coursestudent',
            constraint=models.UniqueConstraint(fields=('course', 'user'), name='unique_course_user'),
        ),
    ]
