# Generated by Django 5.2.6 on 2025-10-29 16:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновление данных')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('term', models.TextField(verbose_name='Термин')),
                ('definition', models.TextField(verbose_name='Определения')),
                ('transcription', models.TextField(blank=True, null=True, verbose_name='Транскрипция')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FlashCardSet',
            fields=[
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновление данных')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
