# Generated by Django 5.2.6 on 2025-10-29 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('flashcards', '0001_initial'),
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='media.image', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='card',
            name='sound',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='media.sound', verbose_name='Аудиофайл'),
        ),
        migrations.AddField(
            model_name='flashcardset',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course', verbose_name='Курсы'),
        ),
        migrations.AddField(
            model_name='card',
            name='flashcard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='flashcards.flashcardset', verbose_name='Набор карточек'),
        ),
    ]
