# Generated by Django 5.2.6 on 2025-11-15 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['-created'], 'verbose_name': 'Карточка', 'verbose_name_plural': 'Карточки'},
        ),
        migrations.AlterModelOptions(
            name='flashcardset',
            options={'ordering': ['-created'], 'verbose_name': 'Набор', 'verbose_name_plural': 'Наборы'},
        ),
    ]
