# Generated by Django 5.2.6 on 2025-11-15 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='folder',
            options={'verbose_name': 'Папка', 'verbose_name_plural': 'Папки'},
        ),
    ]
