# Generated by Django 5.2.6 on 2025-10-17 19:30

import media.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('image_file', models.ImageField(upload_to='images/%Y/%m/%d', validators=[media.models.SizeValueValidator(max_size_mb=3)], verbose_name='Ссылка на файл')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('sound_file', media.models.SoundField(upload_to='sounds/%Y/%m/%d', validators=[media.models.SoundField.validate_audio_file, media.models.SoundField.validate_audio_file_use_mutagen, media.models.SoundField.validate_audio_file, media.models.SoundField.validate_audio_file_use_mutagen], verbose_name='Ссылка на файл')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
