# Generated by Django 5.2.6 on 2025-09-29 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='public',
            new_name='public_id',
        ),
    ]
