# Generated by Django 5.2.6 on 2025-10-17 20:55

import media.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.ImageField(upload_to='files/images/%Y/%m/%d', validators=[media.models.SizeValueValidator(max_size_mb=3)], verbose_name='Ссылка на файл'),
        ),
        migrations.AlterField(
            model_name='sound',
            name='sound_file',
            field=media.models.SoundField(upload_to='files/sounds/%Y/%m/%d', validators=[media.models.SoundField.validate_audio_file, media.models.SoundField.validate_audio_file_use_mutagen, media.models.SoundField.validate_audio_file, media.models.SoundField.validate_audio_file_use_mutagen], verbose_name='Ссылка на файл'),
        ),
    ]
