# Generated by Django 5.2.6 on 2025-10-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_rename_public_image_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.ImageField(upload_to='images/%Y/%m/%d', verbose_name='Ссылка на файл'),
        ),
    ]
