# Generated by Django 5.2.6 on 2025-10-17 21:00

import media.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_alter_image_image_file_alter_sound_sound_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_file',
            new_name='path_file',
        ),
        migrations.RemoveField(
            model_name='sound',
            name='sound_file',
        ),
        migrations.AddField(
            model_name='sound',
            name='path_file',
            field=media.models.SoundField(default=1, upload_to='files/sounds/%Y/%m/%d', validators=[media.models.SoundField.validate_audio_file, media.models.SoundField.validate_audio_file_use_mutagen, media.models.SoundField.validate_audio_file, media.models.SoundField.validate_audio_file_use_mutagen, media.models.SoundField.validate_audio_file, media.models.SoundField.validate_audio_file_use_mutagen], verbose_name='Ссылка на файл'),
            preserve_default=False,
        ),
    ]
