# Generated by Django 5.2.6 on 2025-10-19 07:45

import django.db.models.deletion
import media.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_rename_image_file_image_path_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='uploaded_by_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто загрузил файл'),
        ),
        migrations.AlterField(
            model_name='sound',
            name='path_file',
            field=media.models.SoundField(upload_to='files/sounds/%Y/%m/%d', validators=[media.models.SoundField.validate_audio_file, media.models.SoundField.validate_audio_file_use_mutagen, media.models.SoundField.validate_audio_file, media.models.SoundField.validate_audio_file_use_mutagen], verbose_name='Ссылка на файл'),
        ),
        migrations.AlterField(
            model_name='sound',
            name='uploaded_by_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто загрузил файл'),
        ),
    ]
