# Generated by Django 5.2.6 on 2025-11-15 14:34

import media.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0007_alter_sound_path_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-created'], 'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterModelOptions(
            name='sound',
            options={'ordering': ['-created'], 'verbose_name': 'Произношение', 'verbose_name_plural': 'Произношения'},
        ),
        migrations.AlterField(
            model_name='sound',
            name='path_file',
            field=media.models.SoundField(upload_to='files/sounds/%Y/%m/%d', validators=[media.models.SoundField.validate_audio_file, media.models.SoundField.validate_audio_file_use_mutagen, media.models.SoundField.validate_audio_file, media.models.SoundField.validate_audio_file_use_mutagen], verbose_name='Ссылка на файл'),
        ),
    ]
