# Generated by Django 5.2.6 on 2025-11-15 19:23

import media.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0008_alter_image_options_alter_sound_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sound',
            name='path_file',
            field=media.models.SoundField(upload_to='files/sounds/%Y/%m/%d', validators=[media.models.SoundField.validate_audio_file, media.models.SoundField.validate_audio_file_use_mutagen, media.models.SoundField.validate_audio_file, media.models.SoundField.validate_audio_file_use_mutagen], verbose_name='Ссылка на файл'),
        ),
    ]
