# Generated by Django 5.2.6 on 2026-01-11 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flashcards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Начало сессии')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Окончание сессии')),
                ('cards_studied', models.IntegerField(default=0, verbose_name='Количество изучаемых карточек')),
                ('cards_known', models.IntegerField(default=0, verbose_name='Количество изученных слов за сессию')),
                ('flashcard_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='flashcards.flashcardset', verbose_name='Набор карточек')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь изучающий карточки')),
            ],
            options={
                'verbose_name': 'Сессия изучения',
                'verbose_name_plural': 'Сессии изучения',
            },
        ),
        migrations.CreateModel(
            name='CardProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_known', models.BooleanField(default=False, verbose_name='Знает/Не знает термин?')),
                ('date_answer', models.DateTimeField(auto_now=True, verbose_name='Дата ответа')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashcards.card', verbose_name='Изучающая карточка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Изучающий')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.studysession', verbose_name='Сессия')),
            ],
            options={
                'verbose_name': 'Прогресс карточки',
                'verbose_name_plural': 'Прогресс карточек',
            },
        ),
        migrations.AddConstraint(
            model_name='studysession',
            constraint=models.UniqueConstraint(fields=('user', 'flashcard_set'), name='unique_user_flashcard_set'),
        ),
        migrations.AddConstraint(
            model_name='cardprogress',
            constraint=models.UniqueConstraint(fields=('user', 'card', 'session'), name='unique_user_card_session'),
        ),
    ]
