# Generated by Django 5.2.6 on 2026-02-20 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('Школа / Лицей / Гимназия', 'School'), ('Колледж / Техникум', 'College'), ('Университет / Институт', 'University'), ('Другое образовательное учреждение', 'Other Edu'), ('Профессиональный преподаватель', 'Pro Teacher'), ('Организация / Компания', 'Organization'), ('Простой пользователь / Энтузиаст', 'Simple User')], default='simple_user', max_length=64, null=True, verbose_name='Тип пользователя'),
        ),
    ]
