# Generated by Django 5.2.6 on 2026-03-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_bio_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, verbose_name='О себе / организации'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('school', 'Школа / Лицей / Гимназия'), ('college', 'Колледж / Техникум'), ('university', 'Университет / Институт'), ('other_edu', 'Другое образовательное учреждение'), ('pro_teacher', 'Профессиональный преподаватель'), ('organization', 'Организация / Компания'), ('simple_user', 'Простой пользователь / Энтузиаст')], default='simple_user', max_length=64, null=True, verbose_name='Тип пользователя'),
        ),
    ]
