# Generated by Django 5.2.6 on 2026-03-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_bio_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('school', 'School'), ('college', 'College'), ('university', 'University'), ('other_edu', 'Other Edu'), ('pro_teacher', 'Pro Teacher'), ('organization', 'Organization'), ('simple_user', 'Simple User')], default='simple_user', max_length=64, null=True, verbose_name='Тип пользователя'),
        ),
    ]
